services:
  mongo:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27018:27017
    volumes:
      - mongo_data_container:/data/db

volumes:
  mongo_data_container:
  #docker compose -p luanvtph45976-mongodb-4rn up -d
